#!/bin/sh
here="$(dirname ${0})"
. "${here}/.prepare"

if [ -z "${1-}" ] || [ ! -d "${1}" ] || [ -z "${2-}" ]; then
  cancel "Syntax: $(basename $0) <input-directory> <output-directory>"
fi
mkdir -p "${output_fullpath}"

if [ -n "${MARVYN_AUDIO_INCLUDES-}" ]; then
  for include in $(echo "${MARVYN_AUDIO_INCLUDES}" | tr ',' '\n'); do find_filter="${find_filter:+${find_filter} -o} -name ${include}"; done
fi
if [ -n "${MARVYN_AUDIO_EXCLUDES-}" ]; then
  for exclude in $(echo "${MARVYN_AUDIO_EXCLUDES}" | tr ',' '\n'); do find_filter="${find_filter:+${find_filter} -a} ! -name ${exclude}"; done
fi

find "${input_fullpath}" -type f ${find_filter:+${find_filter}} | sort | while IFS= read -r input_file; do {
  filepath="${input_file#*"${input_fullpath}/"}"
  output_file="${output_fullpath}/${filepath%.*}.${MARVYN_FFMPEG_OUTPUT_FORMAT:-mp3}"
  mkdir -p "$(dirname "${output_file}")"
  ffmpeg -i "${input_file}" ${MARVYN_FFMPEG_OUTPUT_OPTIONS:+${MARVYN_FFMPEG_OUTPUT_OPTIONS}} "${output_file}"
# redirect input from '/dev/null' so that ffmpeg does not consume the loop's input
} </dev/null; done
