#!/bin/sh
here="$(dirname ${0})"
. "${here}/.prepare"

if [ -z "${1-}" ] || [ ! -d "${1}" ] || [ -z "${2-}" ]; then
  cancel "Syntax: $(basename $0) <input-directory> <output-directory>"
fi
mkdir -p "${output_fullpath}"

find "${input_fullpath}" -type f ! -name "*.jpg" | while IFS= read -r input_file; do {
  filepath="${input_file#*${input_fullpath}/}"
  output_file="${output_fullpath}/${filepath%.*}.${MARVYN_FFMPEG_OUTPUT_FORMAT:-mp3}"
  mkdir -p "$(dirname "${output_file}")"
  ffmpeg -i "${input_file}" ${MARVYN_FFMPEG_OUTPUT_OPTIONS:+${MARVYN_FFMPEG_OUTPUT_OPTIONS}} "${output_file}"
} </dev/null; done
